version: '3.7'
services:
  spicyfruit_db:
    container_name: spicyfruit_db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'spicyfruit'
      MYSQL_USER: 'spicyfruit'
      MYSQL_PASSWORD: 'eRSw9612'
      MYSQL_ROOT_PASSWORD: 'qwmn90_+'
      TZ: 'Etc/GMT'
    expose:
      - '3306'
    volumes:
      - C:\Users\rutvik\Documents\spicyfruit\spicyfruit-database\data:/var/lib/mysql
  spicyfruit_api:
    container_name: spicyfruit_api
    restart: always
    build: ./spicyfruit-api
    depends_on:
      - 'spicyfruit_db'
    expose:
      - '3000'
  spicyfruit_backend:
    container_name: spicyfruit_backend
    restart: always
    build: ./spicyfruit-backend
    volumes:
      - C:\Users\rutvik\Documents\spicyfruit\spicyfruit-backend\src:/var/www/html
      - C:\Users\rutvik\Documents\spicyfruit\spicyfruit-backend\logs:/var/www/logs
    depends_on:
      - 'spicyfruit_api'
    expose:
      - '80'
  spicyfruit_server:
    container_name: spicyfruit_server
    restart: always
    build: ./spicyfruit-server
    volumes:
      - C:\Users\rutvik\Documents\spicyfruit\spicyfruit-frontend\dist:/usr/share/nginx/html
      - C:\Users\rutvik\Documents\spicyfruit\spicyfruit-server\default.conf:/etc/nginx/conf.d/default.conf
      - C:\Users\rutvik\Documents\spicyfruit\spicyfruit-server\logs:/var/log/nginx
    depends_on:
      - 'spicyfruit_backend'
    expose:
      - '80'
networks:
  default:
    name: obs_network
    driver: bridge
